# Generated by Django 6.0.6 on 2026-07-06 14:54

import apps.messaging.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brief_connect', '0002_rename_brief_app_request_status_idx_brief_conne_brief_r_26b8a1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('voice', 'Voice Note')], default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.messaging.models.chat_attachment_upload_to)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='brief_connect.briefengagement')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['engagement', 'created_at'], name='messaging_m_engagem_db6e95_idx')],
            },
        ),
    ]
