# Generated by Django 6.0 on 2025-12-10 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(choices=[('HON', 'Honourable'), ('HON_JUSTICE', 'Honourable Justice'), ('JUSTICE', 'Justice'), ('HIS_LORDSHIP', 'His Lordship'), ('HER_LADYSHIP', 'Her Ladyship'), ('CHIEF_JUDGE', 'Chief Judge'), ('PRESIDENT', 'President'), ('GRAND_KADI', 'Grand Kadi')], default='HON_JUSTICE', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('not_sitting', 'Not Sitting'), ('retired', 'Retired'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('status_note', models.TextField(blank=True, help_text='Reason for current status')),
                ('status_effective_from', models.DateField(blank=True, null=True)),
                ('status_effective_until', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='judges/photos/')),
                ('biography', models.TextField(blank=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('year_of_call', models.PositiveIntegerField(blank=True, null=True)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('areas_of_expertise', models.JSONField(blank=True, default=list)),
                ('previous_positions', models.JSONField(blank=True, default=list)),
                ('sitting_days', models.JSONField(blank=True, default=list, help_text='Default sitting days [0=Monday, 4=Friday]')),
                ('sitting_time_start', models.TimeField(blank=True, null=True)),
                ('sitting_time_end', models.TimeField(blank=True, null=True)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('pending_cases', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('is_chief_judge', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judges', to='courts.court')),
                ('default_courtroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_judges', to='courts.courtroom')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judges', to='courts.division')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='JudgeAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('not_sitting', 'Not Sitting'), ('on_leave', 'On Leave'), ('conference', 'Conference/Meeting'), ('training', 'Training'), ('special_assignment', 'Special Assignment')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('alternate_courtroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.courtroom')),
                ('alternate_judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_for', to='judges.judge')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_records', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='judges.judge')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JudgeLeave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('study', 'Study Leave'), ('sabbatical', 'Sabbatical'), ('special', 'Special Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('acting_judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_periods', to='judges.judge')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='judges.judge')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JudgeRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria', models.CharField(choices=[('punctuality', 'Punctuality'), ('professionalism', 'Professionalism'), ('knowledge', 'Legal Knowledge'), ('fairness', 'Fairness'), ('efficiency', 'Case Management Efficiency')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='judges.judge')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('transfer_order_reference', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='courts.court')),
                ('from_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='courts.division')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='judges.judge')),
                ('to_court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='courts.court')),
                ('to_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='courts.division')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['court', 'status'], name='judges_judg_court_i_404da3_idx'),
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['status', 'is_active'], name='judges_judg_status_d3f9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['last_name', 'first_name'], name='judges_judg_last_na_b5bb66_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeavailability',
            index=models.Index(fields=['judge', 'date'], name='judges_judg_judge_i_cef12d_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeavailability',
            index=models.Index(fields=['date', 'availability'], name='judges_judg_date_6e2cfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='judgeavailability',
            unique_together={('judge', 'date')},
        ),
        migrations.AddIndex(
            model_name='judgeleave',
            index=models.Index(fields=['judge', 'start_date', 'end_date'], name='judges_judg_judge_i_b3a587_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerating',
            index=models.Index(fields=['judge', 'criteria'], name='judges_judg_judge_i_f2a213_idx'),
        ),
    ]
