# Generated by Django 4.2.30 on 2026-06-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['-is_chief_judge', 'last_name', 'first_name']},
        ),
    ]
