# Generated by Django 6.0 on 2025-12-10 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('filed', 'Case Filed'), ('hearing', 'Hearing'), ('adjournment', 'Adjournment'), ('ruling', 'Ruling'), ('judgment', 'Judgment'), ('status_change', 'Status Change'), ('transfer', 'Transfer'), ('document', 'Document Filed'), ('other', 'Other')], max_length=20)),
                ('event_date', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('order_reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('suit_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('old_case_numbers', models.JSONField(blank=True, default=list)),
                ('parties', models.TextField(help_text='Full party description')),
                ('applicant', models.CharField(blank=True, max_length=500)),
                ('respondent', models.CharField(blank=True, max_length=500)),
                ('co_applicants', models.JSONField(blank=True, default=list)),
                ('co_respondents', models.JSONField(blank=True, default=list)),
                ('interested_parties', models.JSONField(blank=True, default=list)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('appeal', 'Appeal'), ('constitutional', 'Constitutional'), ('commercial', 'Commercial'), ('family', 'Family'), ('probate', 'Probate'), ('land', 'Land'), ('admiralty', 'Admiralty'), ('election', 'Election Petition'), ('tax', 'Tax'), ('other', 'Other')], db_index=True, max_length=20)),
                ('matter_type', models.CharField(blank=True, max_length=100)),
                ('subject_matter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('adjourned', 'Adjourned'), ('reserved', 'Reserved for Judgment'), ('judgment', 'Judgment Delivered'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn'), ('struck_out', 'Struck Out'), ('dismissed', 'Dismissed'), ('transferred', 'Transferred'), ('appealed', 'Appealed'), ('concluded', 'Concluded')], db_index=True, default='pending', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('first_hearing_date', models.DateField(blank=True, null=True)),
                ('last_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('judgment_date', models.DateField(blank=True, null=True)),
                ('judgment_summary', models.TextField(blank=True)),
                ('ruling', models.TextField(blank=True)),
                ('counsel_for_applicant', models.TextField(blank=True)),
                ('counsel_for_respondent', models.TextField(blank=True)),
                ('total_adjournments', models.PositiveIntegerField(default=0)),
                ('total_hearings', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('scraper', 'Web Scraper'), ('cause_list', 'Cause List'), ('filing', 'E-Filing'), ('import', 'Data Import')], default='manual', max_length=50)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='courts.court')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='courts.division')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='judges.judge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('originating', 'Originating Process'), ('statement_of_claim', 'Statement of Claim'), ('statement_of_defence', 'Statement of Defence'), ('motion', 'Motion'), ('affidavit', 'Affidavit'), ('exhibit', 'Exhibit'), ('ruling', 'Ruling'), ('judgment', 'Judgment'), ('order', 'Order'), ('brief', 'Brief'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='case_documents/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('filed_by', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'ordering': ['-filing_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseHearing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('courtroom', models.CharField(blank=True, max_length=100)),
                ('outcome', models.CharField(choices=[('adjourned', 'Adjourned'), ('hearing', 'Hearing Held'), ('ruling', 'Ruling Delivered'), ('judgment', 'Judgment Delivered'), ('struck_out', 'Struck Out'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn'), ('dismissed', 'Dismissed'), ('mention', 'Mention'), ('other', 'Other')], default='adjourned', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('adjournment_reason', models.TextField(blank=True)),
                ('applicant_present', models.BooleanField(null=True)),
                ('respondent_present', models.BooleanField(null=True)),
                ('counsel_applicant_present', models.BooleanField(null=True)),
                ('counsel_respondent_present', models.BooleanField(null=True)),
                ('proceedings', models.TextField(blank=True)),
                ('orders', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
