# Generated by Django 6.0 on 2025-12-10 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('cause_lists', '0001_initial'),
        ('courts', '0001_initial'),
        ('judges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casehearing',
            name='cause_list_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearing_records', to='cause_lists.causelistentry'),
        ),
        migrations.AddField(
            model_name='casehearing',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to='judges.judge'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casetimeline',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casetimeline',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casedocument'),
        ),
        migrations.AddField(
            model_name='casetimeline',
            name='hearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casehearing'),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='from_court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_transferred_out', to='courts.court'),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='from_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_transferred_out', to='judges.judge'),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='to_court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_transferred_in', to='courts.court'),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='to_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_transferred_in', to='judges.judge'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_case_nu_a07304_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['court', 'status'], name='cases_case_court_i_5c776d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['judge', 'status'], name='cases_case_judge_i_fc91dd_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['next_hearing_date'], name='cases_case_next_he_30bbed_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_type', 'status'], name='cases_case_case_ty_f52464_idx'),
        ),
        migrations.AddIndex(
            model_name='casehearing',
            index=models.Index(fields=['case', 'date'], name='cases_caseh_case_id_89616a_idx'),
        ),
        migrations.AddIndex(
            model_name='casehearing',
            index=models.Index(fields=['date', 'outcome'], name='cases_caseh_date_cda9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='casetimeline',
            index=models.Index(fields=['case', 'event_date'], name='cases_caset_case_id_a6d36e_idx'),
        ),
    ]
