# Generated by Django 6.0.6 on 2026-07-06 14:30

import apps.brief_connect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='briefapplication',
            new_name='brief_conne_brief_r_26b8a1_idx',
            old_name='brief_app_request_status_idx',
        ),
        migrations.RenameIndex(
            model_name='briefapplication',
            new_name='brief_conne_applica_417018_idx',
            old_name='brief_app_applicant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='briefengagement',
            new_name='brief_conne_holding_1d874d_idx',
            old_name='brief_eng_holder_status_idx',
        ),
        migrations.RenameIndex(
            model_name='briefengagement',
            new_name='brief_conne_request_10655d_idx',
            old_name='brief_eng_requester_status_idx',
        ),
        migrations.RenameIndex(
            model_name='briefrequest',
            new_name='brief_conne_status_adb8d5_idx',
            old_name='brief_req_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='briefrequest',
            new_name='brief_conne_court_i_88f6bc_idx',
            old_name='brief_req_court_date_idx',
        ),
        migrations.RenameIndex(
            model_name='briefrequest',
            new_name='brief_conne_request_d1e1c3_idx',
            old_name='brief_req_requester_status_idx',
        ),
        migrations.RenameIndex(
            model_name='briefrequest',
            new_name='brief_conne_hearing_e89e8e_idx',
            old_name='brief_req_hearing_date_idx',
        ),
        migrations.RenameIndex(
            model_name='briefreview',
            new_name='brief_conne_reviewe_524a62_idx',
            old_name='brief_rev_reviewee_idx',
        ),
        migrations.AddField(
            model_name='briefapplication',
            name='anon_code',
            field=models.CharField(default=apps.brief_connect.models.generate_anon_code, editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='anon_code',
            field=models.CharField(default=apps.brief_connect.models.generate_anon_code, editable=False, max_length=8),
        ),
    ]
