# Generated by Django 6.0.6 on 2026-07-06 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_connect', '0002_rename_brief_app_request_status_idx_brief_conne_brief_r_26b8a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfCompletion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='brief_connect/proof_of_completion/')),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_completion', to='brief_connect.briefengagement')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
