# Generated by Django 6.0.6 on 2026-07-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_connect', '0004_feeoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20),
        ),
    ]
