# Generated by Django 6.0 on 2025-12-10 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('courts', '0001_initial'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('filing_type', models.CharField(choices=[('originating', 'Originating Process'), ('motion', 'Motion'), ('affidavit', 'Affidavit'), ('brief', 'Brief'), ('reply', 'Reply'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('applicant', models.CharField(max_length=500)),
                ('respondent', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('corrections_required', 'Corrections Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('filed', 'Filed')], db_index=True, default='draft', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('filing_number', models.CharField(blank=True, max_length=100)),
                ('filing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings', to='cases.case')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='courts.court')),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings', to='firms.lawfirm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilingComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='efiling.filing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('main', 'Main Document'), ('affidavit', 'Affidavit'), ('exhibit', 'Exhibit'), ('supporting', 'Supporting Document')], max_length=20)),
                ('file', models.FileField(upload_to='filings/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='efiling.filing')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['filed_by', 'status'], name='efiling_fil_filed_b_d1494a_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['court', 'status'], name='efiling_fil_court_i_826182_idx'),
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['reference_number'], name='efiling_fil_referen_dd23d0_idx'),
        ),
    ]
