# Generated by Django 6.0.6 on 2026-07-06 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brief_connect', '0003_proofofcompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Funding'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=20)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='brief_connect.briefengagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerBankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bank_code', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('amount_kobo', models.BigIntegerField()),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payments.lawyerbankaccount')),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payments.escrowaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('amount_kobo', models.BigIntegerField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.escrowaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
