# Generated by Django 6.0 on 2025-12-10 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('courts', '0001_initial'),
        ('judges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sitting', 'Sitting'), ('adjourned', 'Adjourned'), ('not_sitting', 'Not Sitting'), ('risen', 'Risen'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status_note', models.TextField(blank=True)),
                ('adjournment_reason', models.TextField(blank=True)),
                ('not_sitting_reason', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cause_lists/pdfs/')),
                ('pdf_file_size', models.PositiveIntegerField(default=0)),
                ('pdf_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('upload', 'PDF Upload'), ('scraper', 'Web Scraper'), ('api', 'API Import')], default='manual', max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_lists', to='courts.court')),
                ('courtroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_lists', to='courts.courtroom')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_lists', to='judges.judge')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_lists', to='courts.panel')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_cause_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'court__name'],
            },
        ),
        migrations.CreateModel(
            name='CauseListEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_number', models.CharField(db_index=True, max_length=100)),
                ('suit_number', models.CharField(blank=True, max_length=100)),
                ('parties', models.TextField(help_text='Full party names as they appear on the list')),
                ('applicant', models.CharField(blank=True, max_length=500)),
                ('respondent', models.CharField(blank=True, max_length=500)),
                ('matter_type', models.CharField(blank=True, max_length=100)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('appeal', 'Appeal'), ('motion', 'Motion'), ('ruling', 'Ruling'), ('judgment', 'Judgment'), ('mention', 'Mention'), ('hearing', 'Hearing'), ('other', 'Other')], default='civil', max_length=50)),
                ('order_number', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('courtroom', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('called', 'Called'), ('in_progress', 'In Progress'), ('adjourned', 'Adjourned'), ('struck_out', 'Struck Out'), ('settled', 'Settled'), ('judgment', 'Judgment Delivered'), ('ruling', 'Ruling Delivered'), ('completed', 'Completed')], default='scheduled', max_length=50)),
                ('outcome', models.TextField(blank=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('adjournment_reason', models.TextField(blank=True)),
                ('counsel_for_applicant', models.TextField(blank=True)),
                ('counsel_for_respondent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_list_entries', to='cases.case')),
                ('cause_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cause_lists.causelist')),
            ],
            options={
                'ordering': ['order_number', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='CauseListChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('time_changed', 'Time Changed'), ('courtroom_changed', 'Courtroom Changed'), ('case_added', 'Case Added'), ('case_removed', 'Case Removed'), ('case_reordered', 'Case Reordered'), ('adjourned', 'Adjourned'), ('cancelled', 'Cancelled')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('notifications_sent', models.BooleanField(default=False)),
                ('notifications_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cause_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='cause_lists.causelist')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_list_changes', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='cause_lists.causelistentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CauseListSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('notify_new_list', models.BooleanField(default=True)),
                ('notify_changes', models.BooleanField(default=True)),
                ('notify_status_change', models.BooleanField(default=True)),
                ('notify_adjournment', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_list_subscribers', to='courts.court')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_list_subscribers', to='judges.judge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_list_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CauseListTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('docx', 'Word Document'), ('xlsx', 'Excel')], default='pdf', max_length=20)),
                ('parsing_rules', models.JSONField(default=dict)),
                ('field_mappings', models.JSONField(default=dict)),
                ('regex_patterns', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_list_templates', to='courts.court')),
            ],
            options={
                'ordering': ['court__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='causelist',
            index=models.Index(fields=['date', 'status'], name='cause_lists_date_c81ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='causelist',
            index=models.Index(fields=['court', 'date'], name='cause_lists_court_i_2bdcff_idx'),
        ),
        migrations.AddIndex(
            model_name='causelist',
            index=models.Index(fields=['judge', 'date'], name='cause_lists_judge_i_1eba4b_idx'),
        ),
        migrations.AddIndex(
            model_name='causelist',
            index=models.Index(fields=['status', 'date'], name='cause_lists_status_e09084_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='causelist',
            unique_together={('court', 'judge', 'date')},
        ),
        migrations.AddIndex(
            model_name='causelistentry',
            index=models.Index(fields=['cause_list', 'order_number'], name='cause_lists_cause_l_4912d6_idx'),
        ),
        migrations.AddIndex(
            model_name='causelistentry',
            index=models.Index(fields=['case_number'], name='cause_lists_case_nu_04036c_idx'),
        ),
        migrations.AddIndex(
            model_name='causelistentry',
            index=models.Index(fields=['status'], name='cause_lists_status_eec3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='causelistchange',
            index=models.Index(fields=['cause_list', 'change_type'], name='cause_lists_cause_l_7f6042_idx'),
        ),
        migrations.AddIndex(
            model_name='causelistchange',
            index=models.Index(fields=['created_at'], name='cause_lists_created_8c021a_idx'),
        ),
        migrations.AddIndex(
            model_name='causelistsubscription',
            index=models.Index(fields=['user', 'is_active'], name='cause_lists_user_id_f3d5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='causelistsubscription',
            index=models.Index(fields=['court', 'is_active'], name='cause_lists_court_i_217cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='causelistsubscription',
            index=models.Index(fields=['judge', 'is_active'], name='cause_lists_judge_i_912f94_idx'),
        ),
    ]
