# Generated by Django 4.2.30 on 2026-06-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause_lists', '0002_causelistimage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='causelistimage',
            new_name='cause_lists_cause_l_a8e02c_idx',
            old_name='cause_lists_cl_img_cl_page_idx',
        ),
        migrations.AlterField(
            model_name='causelistimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='causelistimage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
