# Generated by Django 6.0.6 on 2026-07-06 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpoint', models.CharField(choices=[('posting', 'Posting a Brief Request'), ('applying', 'Applying to a Brief Request'), ('escrow', 'Funding Escrow'), ('completion', 'Confirming or Rejecting Completion')], db_index=True, max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['checkpoint', 'is_active'], name='policies_po_checkpo_bc1a32_idx')],
                'unique_together': {('checkpoint', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='policies.policydocument')),
            ],
            options={
                'unique_together': {('user', 'policy')},
            },
        ),
    ]
