# Generated by Django 6.0 on 2025-12-10 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('court_type', models.CharField(choices=[('SC', 'Supreme Court'), ('CA', 'Court of Appeal'), ('FHC', 'Federal High Court'), ('NIC', 'National Industrial Court'), ('SHC', 'State High Court'), ('FCT', 'FCT High Court'), ('SAC', 'Sharia Court of Appeal'), ('CCA', 'Customary Court of Appeal'), ('MC', 'Magistrate Court'), ('AC', 'Area Court'), ('CC', 'Customary Court')], db_index=True, max_length=5)),
                ('state', models.CharField(choices=[('AB', 'Abia'), ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), ('FC', 'FCT Abuja'), ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), ('SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara')], db_index=True, max_length=3)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('jurisdiction', models.TextField(blank=True, help_text="Description of court's jurisdiction")),
                ('jurisdiction_areas', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('chief_judge_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('working_days', models.JSONField(blank=True, default=list, help_text='Days court is in session [0=Monday, 4=Friday]')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text="Working hours {start: '08:00', end: '16:00'}")),
                ('total_judges', models.PositiveIntegerField(default=0)),
                ('total_divisions', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['court_type', 'state'], name='courts_cour_court_t_710683_idx'), models.Index(fields=['code'], name='courts_cour_code_d5c88d_idx'), models.Index(fields=['is_active'], name='courts_cour_is_acti_bc541b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourtContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('registrar', 'Registrar'), ('chief_registrar', 'Chief Registrar'), ('deputy_registrar', 'Deputy Registrar'), ('information', 'Information Desk'), ('filing', 'Filing Office'), ('records', 'Records Office'), ('accounts', 'Accounts'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='courts.court')),
            ],
            options={
                'ordering': ['contact_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourtHoliday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('public', 'Public Holiday'), ('vacation', 'Court Vacation'), ('special', 'Special Holiday')], max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='courts.court')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourtRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('rule', 'Court Rule'), ('practice_direction', 'Practice Direction'), ('circular', 'Circular'), ('notice', 'Notice'), ('guideline', 'Guideline')], max_length=50)),
                ('document', models.FileField(upload_to='court_rules/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='courts.court')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='courts.courtrule')),
            ],
            options={
                'ordering': ['-effective_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('head_judge_id', models.UUIDField(blank=True, null=True)),
                ('total_judges', models.PositiveIntegerField(default=0)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='courts.court')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Courtroom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('has_video_conferencing', models.BooleanField(default=False)),
                ('has_recording', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtrooms', to='courts.court')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courtrooms', to='courts.division')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('presiding_judge_id', models.UUIDField(blank=True, null=True)),
                ('member_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('assigned_categories', models.JSONField(blank=True, default=list)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='courts.court')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['court', 'is_active'], name='courts_divi_court_i_5ffeb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('court', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='courtroom',
            unique_together={('court', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='panel',
            unique_together={('court', 'code')},
        ),
    ]
