# Generated by Django 6.0.6 on 2026-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('cause_list_new', 'New Cause List'), ('cause_list_update', 'Cause List Updated'), ('cause_list_status', 'Cause List Status Change'), ('case_adjournment', 'Case Adjourned'), ('not_sitting', 'Not Sitting Notice'), ('time_change', 'Time Changed'), ('courtroom_change', 'Courtroom Changed'), ('case_update', 'Case Update'), ('case_on_docket', 'Case on Docket'), ('judge_status', 'Judge Status Change'), ('filing_update', 'Filing Update'), ('filing_approved', 'Filing Approved'), ('filing_rejected', 'Filing Rejected'), ('reminder', 'Reminder'), ('system', 'System Notification'), ('brief_connect_new_request', 'New Brief Request'), ('brief_connect_application', 'Brief Application Received'), ('brief_connect_accepted', 'Brief Application Accepted'), ('brief_connect_rejected', 'Brief Application Not Selected'), ('brief_connect_completed', 'Brief Engagement Completed')], db_index=True, max_length=30),
        ),
    ]
